# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9addba3cc6d12653b8b4de5eb4ed2670"
name = "remix-chat"
handle = "remix-chat-145"
application_url = "https://horse-serving-ferrari-native.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "diswir.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://horse-serving-ferrari-native.trycloudflare.com/auth/callback",
  "https://horse-serving-ferrari-native.trycloudflare.com/auth/shopify/callback",
  "https://horse-serving-ferrari-native.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
